language: java
jdk:
        - openjdk8
addons:
        sonarcloud:
                organization: torkin1
                token:
                        secure: 22c4183d1843a915e7ce6bd5baf5fb2d60c98fdc
        apt:
                packages:
                        openjdk-8-jre-headless
before-install:
        - sudo apt-get update -q
        - sudo apt-get install ant-optional openjfx links -y
script:
        - ant -v build test
        - sonar-scanner
deploy:
        provider: pages
        skip_cleanup: true
        github_token:  $OK
        keep_history: true
        on:
            branch: master
        local_dir: coverage
        verbose: true


